/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.acme.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class relatives extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3716778752937531081L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"relatives\",\"namespace\":\"com.acme.avro\",\"fields\":[{\"name\":\"Asya\",\"type\":\"int\"},{\"name\":\"Farkhat\",\"type\":\"int\"},{\"name\":\"Ruslan\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<relatives> ENCODER =
      new BinaryMessageEncoder<relatives>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<relatives> DECODER =
      new BinaryMessageDecoder<relatives>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<relatives> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<relatives> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<relatives> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<relatives>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this relatives to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a relatives from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a relatives instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static relatives fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int Asya;
  private int Farkhat;
  private int Ruslan;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public relatives() {}

  /**
   * All-args constructor.
   * @param Asya The new value for Asya
   * @param Farkhat The new value for Farkhat
   * @param Ruslan The new value for Ruslan
   */
  public relatives(java.lang.Integer Asya, java.lang.Integer Farkhat, java.lang.Integer Ruslan) {
    this.Asya = Asya;
    this.Farkhat = Farkhat;
    this.Ruslan = Ruslan;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Asya;
    case 1: return Farkhat;
    case 2: return Ruslan;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Asya = (java.lang.Integer)value$; break;
    case 1: Farkhat = (java.lang.Integer)value$; break;
    case 2: Ruslan = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Asya' field.
   * @return The value of the 'Asya' field.
   */
  public int getAsya() {
    return Asya;
  }


  /**
   * Sets the value of the 'Asya' field.
   * @param value the value to set.
   */
  public void setAsya(int value) {
    this.Asya = value;
  }

  /**
   * Gets the value of the 'Farkhat' field.
   * @return The value of the 'Farkhat' field.
   */
  public int getFarkhat() {
    return Farkhat;
  }


  /**
   * Sets the value of the 'Farkhat' field.
   * @param value the value to set.
   */
  public void setFarkhat(int value) {
    this.Farkhat = value;
  }

  /**
   * Gets the value of the 'Ruslan' field.
   * @return The value of the 'Ruslan' field.
   */
  public int getRuslan() {
    return Ruslan;
  }


  /**
   * Sets the value of the 'Ruslan' field.
   * @param value the value to set.
   */
  public void setRuslan(int value) {
    this.Ruslan = value;
  }

  /**
   * Creates a new relatives RecordBuilder.
   * @return A new relatives RecordBuilder
   */
  public static com.acme.avro.relatives.Builder newBuilder() {
    return new com.acme.avro.relatives.Builder();
  }

  /**
   * Creates a new relatives RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new relatives RecordBuilder
   */
  public static com.acme.avro.relatives.Builder newBuilder(com.acme.avro.relatives.Builder other) {
    if (other == null) {
      return new com.acme.avro.relatives.Builder();
    } else {
      return new com.acme.avro.relatives.Builder(other);
    }
  }

  /**
   * Creates a new relatives RecordBuilder by copying an existing relatives instance.
   * @param other The existing instance to copy.
   * @return A new relatives RecordBuilder
   */
  public static com.acme.avro.relatives.Builder newBuilder(com.acme.avro.relatives other) {
    if (other == null) {
      return new com.acme.avro.relatives.Builder();
    } else {
      return new com.acme.avro.relatives.Builder(other);
    }
  }

  /**
   * RecordBuilder for relatives instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<relatives>
    implements org.apache.avro.data.RecordBuilder<relatives> {

    private int Asya;
    private int Farkhat;
    private int Ruslan;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.acme.avro.relatives.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Asya)) {
        this.Asya = data().deepCopy(fields()[0].schema(), other.Asya);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.Farkhat)) {
        this.Farkhat = data().deepCopy(fields()[1].schema(), other.Farkhat);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.Ruslan)) {
        this.Ruslan = data().deepCopy(fields()[2].schema(), other.Ruslan);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing relatives instance
     * @param other The existing instance to copy.
     */
    private Builder(com.acme.avro.relatives other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Asya)) {
        this.Asya = data().deepCopy(fields()[0].schema(), other.Asya);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Farkhat)) {
        this.Farkhat = data().deepCopy(fields()[1].schema(), other.Farkhat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Ruslan)) {
        this.Ruslan = data().deepCopy(fields()[2].schema(), other.Ruslan);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'Asya' field.
      * @return The value.
      */
    public int getAsya() {
      return Asya;
    }


    /**
      * Sets the value of the 'Asya' field.
      * @param value The value of 'Asya'.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder setAsya(int value) {
      validate(fields()[0], value);
      this.Asya = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Asya' field has been set.
      * @return True if the 'Asya' field has been set, false otherwise.
      */
    public boolean hasAsya() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Asya' field.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder clearAsya() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Farkhat' field.
      * @return The value.
      */
    public int getFarkhat() {
      return Farkhat;
    }


    /**
      * Sets the value of the 'Farkhat' field.
      * @param value The value of 'Farkhat'.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder setFarkhat(int value) {
      validate(fields()[1], value);
      this.Farkhat = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Farkhat' field has been set.
      * @return True if the 'Farkhat' field has been set, false otherwise.
      */
    public boolean hasFarkhat() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Farkhat' field.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder clearFarkhat() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Ruslan' field.
      * @return The value.
      */
    public int getRuslan() {
      return Ruslan;
    }


    /**
      * Sets the value of the 'Ruslan' field.
      * @param value The value of 'Ruslan'.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder setRuslan(int value) {
      validate(fields()[2], value);
      this.Ruslan = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Ruslan' field has been set.
      * @return True if the 'Ruslan' field has been set, false otherwise.
      */
    public boolean hasRuslan() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Ruslan' field.
      * @return This builder.
      */
    public com.acme.avro.relatives.Builder clearRuslan() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public relatives build() {
      try {
        relatives record = new relatives();
        record.Asya = fieldSetFlags()[0] ? this.Asya : (java.lang.Integer) defaultValue(fields()[0]);
        record.Farkhat = fieldSetFlags()[1] ? this.Farkhat : (java.lang.Integer) defaultValue(fields()[1]);
        record.Ruslan = fieldSetFlags()[2] ? this.Ruslan : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<relatives>
    WRITER$ = (org.apache.avro.io.DatumWriter<relatives>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<relatives>
    READER$ = (org.apache.avro.io.DatumReader<relatives>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.Asya);

    out.writeInt(this.Farkhat);

    out.writeInt(this.Ruslan);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.Asya = in.readInt();

      this.Farkhat = in.readInt();

      this.Ruslan = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.Asya = in.readInt();
          break;

        case 1:
          this.Farkhat = in.readInt();
          break;

        case 2:
          this.Ruslan = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










